<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>Data Frames</title>
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    span.underline{text-decoration: underline;}
    div.column{display: inline-block; vertical-align: top; width: 50%;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      {   }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span.al { color: #ff0000; font-weight: bold; } /* Alert */
    code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
    code span.at { color: #7d9029; } /* Attribute */
    code span.bn { color: #40a070; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #4070a0; } /* Char */
    code span.cn { color: #880000; } /* Constant */
    code span.co { color: #60a0b0; font-style: italic; } /* Comment */
    code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
    code span.do { color: #ba2121; font-style: italic; } /* Documentation */
    code span.dt { color: #902000; } /* DataType */
    code span.dv { color: #40a070; } /* DecVal */
    code span.er { color: #ff0000; font-weight: bold; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #40a070; } /* Float */
    code span.fu { color: #06287e; } /* Function */
    code span.im { } /* Import */
    code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
    code span.kw { color: #007020; font-weight: bold; } /* Keyword */
    code span.op { color: #666666; } /* Operator */
    code span.ot { color: #007020; } /* Other */
    code span.pp { color: #bc7a00; } /* Preprocessor */
    code span.sc { color: #4070a0; } /* SpecialChar */
    code span.ss { color: #bb6688; } /* SpecialString */
    code span.st { color: #4070a0; } /* String */
    code span.va { color: #19177c; } /* Variable */
    code span.vs { color: #4070a0; } /* VerbatimString */
    code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <link href="../style/newstyle.css" rel="stylesheet" type="text/css">
  <link rel="icon" type="image/png" href="../style/imgs/favicon.png">
  <style>
    /* topic-page-specific overrides */
    body { padding-top: 0; }
    .topic-body { max-width: 880px; margin: 1.5rem auto; padding: 0 1.5rem; }
    .topic-body h1 { font-size: 1.8rem; margin-bottom: 0.4rem; color: #820000; }
    .topic-body h2 { font-size: 1.3rem; margin-top: 2rem; }
    .topic-body h3 { font-size: 1.1rem; margin-top: 1.3rem; }
    .topic-body img { max-width: 100%; height: auto; }
    .topic-body figure { margin: 1rem 0; }
    .topic-body figcaption { display: none; }
    .topic-body pre { background: #f6f6f6; padding: 0.6rem 0.8rem; border-radius: 3px; overflow-x: auto; }
    .topic-body pre code { background: transparent; }
    .topic-body code { background: #f0f0f0; padding: 0.1rem 0.3rem; border-radius: 2px; font-size: 0.92em; }
    .topic-crumbs { color: #666; font-size: 0.9rem; margin-bottom: 1rem; }
    .topic-crumbs a { color: #134a85; }
  </style>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark">
  <a href="../index.html">
    <img src="../style/imgs/mie.png" style="height:40px; float: left; margin-left: 20px; margin-right: 20px;" alt="MIE logo">
  </a>
  <a class="navbar-brand" href="../index.html">MIE1626</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#topicNavbar" aria-controls="topicNavbar" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="topicNavbar">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><a class="nav-link" href="../materials/1626s26/mie1626_syllabus.pdf">Syllabus</a></li>
      <li class="nav-item"><a class="nav-link" href="../lectures.html">Lectures</a></li>
      <li class="nav-item"><a class="nav-link" href="../index.html#mini-projects">Mini-projects</a></li>
      <li class="nav-item"><a class="nav-link" href="../index.html#project">Project</a></li>
      <li class="nav-item"><a class="nav-link" href="../index.html#info">Course info</a></li>
      <li class="nav-item"><a class="nav-link" href="../index.html#logistics">Logistics</a></li>
      <li class="nav-item"><a class="nav-link" href="../index.html#resources">Resources</a></li>
    </ul>
  </div>
</nav>

<div class="topic-body">
<p class="topic-crumbs"><a href="../lectures.html">&larr; Lecture calendar</a></p>
<header id="title-block-header">
<h1 class="title">Data Frames</h1>
</header>
<h2 id="data-frames">Data frames</h2>
<p>The usual way that you work with data in R is <strong>data frames</strong>. A data frame is basically a table. The advantage is you don’t have to manually keep track of what corresponds to what — if you have a table, you just have rows.</p>
<p>A lot of the time you just read it from a file, so you do not have to define it manually. But if you do, in R it works like this: you say <code>data.frame</code>, then the name of the column, then the contents of the column as a vector.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true"></a>df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true"></a>  <span class="dt">offer =</span> <span class="kw">c</span>(<span class="dv">241</span>, <span class="dv">590</span>, <span class="dv">533</span>, <span class="dv">425</span>, <span class="dv">261</span>),</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true"></a>  <span class="dt">spec =</span> <span class="kw">c</span>(<span class="st">&quot;family doc&quot;</span>, <span class="st">&quot;cardiologist&quot;</span>, <span class="st">&quot;orthopedic&quot;</span>, <span class="st">&quot;dermatologist&quot;</span>, <span class="st">&quot;psychiatrist&quot;</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true"></a>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true"></a>df</span></code></pre></div>
<pre><code>##   offer          spec
## 1   241    family doc
## 2   590  cardiologist
## 3   533    orthopedic
## 4   425 dermatologist
## 5   261  psychiatrist</code></pre>
<p>This is now a table.</p>
<h2 id="the-babynames-data-set">The babynames data set</h2>
<p>You need to do this the first time:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true"></a><span class="kw">install.packages</span>(<span class="st">&quot;babynames&quot;</span>)</span></code></pre></div>
<p>Once installed:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true"></a><span class="kw">library</span>(babynames)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true"></a><span class="kw">head</span>(babynames)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 5
##    year sex   name          n   prop
##   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;  &lt;dbl&gt;
## 1  1880 F     Mary       7065 0.0724
## 2  1880 F     Anna       2604 0.0267
## 3  1880 F     Emma       2003 0.0205
## 4  1880 F     Elizabeth  1939 0.0199
## 5  1880 F     Minnie     1746 0.0179
## 6  1880 F     Margaret   1578 0.0162</code></pre>
<p>The dataset has the most common names in the US. So in 1880 there were 7,065 Marys registered as being born in the US.</p>
<p>Technically <code>babynames</code> is what is called a <strong>tibble</strong> rather than a plain data frame. A tibble is just a variation on the word “table” that is specific to R. It is basically a special kind of data frame, and prints more nicely.</p>
<h2 id="accessing-rows-and-columns">Accessing rows and columns</h2>
<p>You can access something like row number two, the column <code>year</code>, by doing this:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true"></a>babynames[<span class="dv">2</span>, <span class="st">&quot;year&quot;</span>]</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##    year
##   &lt;dbl&gt;
## 1  1880</code></pre>
<p>Get just the first several rows with <code>head</code>. Get a specific row and column:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true"></a>babynames[<span class="dv">500</span>, <span class="st">&quot;name&quot;</span>]</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   name 
##   &lt;chr&gt;
## 1 Dessa</code></pre>
<p>You can use the column index:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true"></a>babynames[<span class="dv">500</span>, <span class="dv">3</span>]</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   name 
##   &lt;chr&gt;
## 1 Dessa</code></pre>
<p>You can give a range of rows and several columns at once:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true"></a>babynames[<span class="dv">2</span><span class="op">:</span><span class="dv">6</span>, <span class="st">&quot;year&quot;</span>]</span></code></pre></div>
<pre><code>## # A tibble: 5 × 1
##    year
##   &lt;dbl&gt;
## 1  1880
## 2  1880
## 3  1880
## 4  1880
## 5  1880</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true"></a>babynames[<span class="dv">2</span><span class="op">:</span><span class="dv">6</span>, <span class="kw">c</span>(<span class="st">&quot;year&quot;</span>, <span class="st">&quot;name&quot;</span>)]</span></code></pre></div>
<pre><code>## # A tibble: 5 × 2
##    year name     
##   &lt;dbl&gt; &lt;chr&gt;    
## 1  1880 Anna     
## 2  1880 Emma     
## 3  1880 Elizabeth
## 4  1880 Minnie   
## 5  1880 Margaret</code></pre>
<p>You can also access just the data from a particular column using the dollar sign:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true"></a><span class="kw">head</span>(babynames<span class="op">$</span>name)</span></code></pre></div>
<pre><code>## [1] &quot;Mary&quot;      &quot;Anna&quot;      &quot;Emma&quot;      &quot;Elizabeth&quot; &quot;Minnie&quot;    &quot;Margaret&quot;</code></pre>
<p>The dollar sign is subtly different from the bracket syntax: <code>babynames$name</code> gives you a <strong>vector</strong>, whereas <code>babynames["name"]</code> (without a row) gives you a <strong>data frame</strong> that’s just that column.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true"></a><span class="kw">head</span>(babynames[<span class="st">&quot;name&quot;</span>])</span></code></pre></div>
<pre><code>## # A tibble: 6 × 1
##   name     
##   &lt;chr&gt;    
## 1 Mary     
## 2 Anna     
## 3 Emma     
## 4 Elizabeth
## 5 Minnie   
## 6 Margaret</code></pre>
<h2 id="subsetting-rows-with-a-boolean-mask">Subsetting rows with a boolean mask</h2>
<p>You can subset with a boolean mask. For example, if you want the data from the year 1999 with <code>sex == "F"</code>:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true"></a>babies99 &lt;-<span class="st"> </span>babynames[babynames<span class="op">$</span>year <span class="op">==</span><span class="st"> </span><span class="dv">1999</span> <span class="op">&amp;</span><span class="st"> </span>babynames<span class="op">$</span>sex <span class="op">==</span><span class="st"> &quot;F&quot;</span>, ]</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true"></a><span class="kw">head</span>(babies99)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 5
##    year sex   name         n    prop
##   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;    &lt;int&gt;   &lt;dbl&gt;
## 1  1999 F     Emily    26539 0.0136 
## 2  1999 F     Hannah   21673 0.0111 
## 3  1999 F     Alexis   19234 0.00988
## 4  1999 F     Sarah    19102 0.00982
## 5  1999 F     Samantha 19036 0.00978
## 6  1999 F     Ashley   18136 0.00932</code></pre>
<p>What happened: <code>babynames$year == 1999</code> is a vector of <code>TRUE</code>/<code>FALSE</code>, <code>babynames$sex == "F"</code> is another vector of <code>TRUE</code>/<code>FALSE</code>. We combined them with <code>&amp;</code> so the entry is <code>TRUE</code> only when the year is 1999 and the sex is F. Then we said all of the columns by leaving the second slot empty.</p>
<p>We can get the maximum count from <code>babies99</code>:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true"></a><span class="kw">max</span>(babies99<span class="op">$</span>n)</span></code></pre></div>
<pre><code>## [1] 26539</code></pre>
<p>And, in the same way that we did with the salaries, we can find the name that corresponds to the maximum:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true"></a>babies99[babies99<span class="op">$</span>n <span class="op">==</span><span class="st"> </span><span class="kw">max</span>(babies99<span class="op">$</span>n), <span class="st">&quot;name&quot;</span>]</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   name 
##   &lt;chr&gt;
## 1 Emily</code></pre>
<h2 id="a-function-most-common-name-for-a-year-and-sex">A function: most common name for a year and sex</h2>
<p>Let’s say that we want the most common name for a particular year and sex. One way: get a data frame with just that year and sex, then use the same trick as before — find rows where the count equals the maximum and pick out the name.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true"></a>most_common &lt;-<span class="st"> </span><span class="cf">function</span>(year, sex){</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true"></a>  df &lt;-<span class="st"> </span>babynames[babynames<span class="op">$</span>year <span class="op">==</span><span class="st"> </span>year <span class="op">&amp;</span><span class="st"> </span>babynames<span class="op">$</span>sex <span class="op">==</span><span class="st"> </span>sex, ]</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true"></a>  df[df<span class="op">$</span>n <span class="op">==</span><span class="st"> </span><span class="kw">max</span>(df<span class="op">$</span>n), <span class="st">&quot;name&quot;</span>]</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true"></a>}</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true"></a><span class="kw">most_common</span>(<span class="dv">1999</span>, <span class="st">&quot;F&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   name 
##   &lt;chr&gt;
## 1 Emily</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true"></a><span class="kw">most_common</span>(<span class="dv">1880</span>, <span class="st">&quot;M&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   name 
##   &lt;chr&gt;
## 1 John</code></pre>
</div>
</body>
</html>
